### ISSUE TITLE
New MET data sources

### ISSUE THREAD

**Issue by mikejohnson51** [mikejohnson51/HydroData#18]
WeatherUnderground has changed there website from static to dynamic

New options are the IOWA mesonet and the EU site. This require airports to be called by their SYNOP rather then ICAO id.

**Comment by dblodgett-usgs** [comment]
Side note, if you haven't seen these services: http://www.rcc-acis.org/docs_webservices.html they may be helpful to the cause. Pretty solid and include all the GHCN and SNOTEL data among other things

**Comment by mikejohnson51** [comment]
Hi Dave,

This is awesome,

There are already functions for grabbing most of the station IDs/ subset parameters that could be used here!

On a side note, do you have any suggestions for packaging “big” (by package standards - ie 22mb .RDA file) data?

I’ve seen the inst/extdata approach but am not sure its the only option.

If there is a nice way there is a pretty quick way of subsetting and discoverying COMIDs that could help both our packages.

Thanks!

**Comment by dblodgett-usgs** [comment]
22mb is a lot to put in your package. The first thing is to make sure you've got compression on your rda file. I'd suggest perusing this: http://r-pkgs.had.co.nz/data.html for your options. I'm planning on implementing some pretty lightweight methods for discovery of catchments. Got started on that over here: https://dblodgett-usgs.github.io/nhdplusTools/reference/discover_nhdplus_id.html and will be adding some stuff from the Network Linked Data Index before too long. (https://owi.usgs.gov/blog/nldi-intro/)

**Comment by mikejohnson51** [comment]
Hi Dave, 

Thanks! This is helpful. Using a better compression sent it to 12 MB (still large). The discover NHD you have is great for finding the COMID catchments. Mostly I was hoping to use the dataset in a project building up tools to subset NWM output (its part of a COMET grant I am working on). I thought it would be nice here as well, but its probably more trouble then it is worth. I will need to figure out storing it for use in the other package though. A problem for another day luckily!

**Comment by mikejohnson51** [comment]
Closing this to reopen a "Integrate with RCC-ACIS
