### ISSUE TITLE
Find WBD fails on large queries

### ISSUE THREAD

**Issue by jsta** [mikejohnson51/HydroData#26]
```
getAOI(state = c("RI")) %>% findWBD()
```
> works

```
getAOI(state = c("MI")) %>% findWBD()
```
> fails with error: 
> Cannot open data source https://hydro.nationalmap.gov/arcgis/rest/services ...
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Open failed.
In addition: Warning message:
In CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  GDAL Error 4: Failed to read GeoJSON data

**Comment by jsta** [comment]
Hmm, now it doesn't seem related to state area because `state = c("WY")` works and Wyoming is larger than Michigan.

**Comment by mikejohnson51** [comment]
I started looking at it and noticed the same about area. The documentation about the REST API is limited but my guess is that it has to do with the number of records that can be returned from a singe call... I am trying a crude fix for now and I'll send it your way. If it helps I can work on making it more elegant. 

A quick solution if looking only for HUC8s would be: 

```r
yy = getAOI(state = 'MI') %>% query_cida(type = 'huc08')
```


Thanks for the heads up!

**Comment by mikejohnson51** [comment]
fixed here [here](https://github.com/mikejohnson51/HydroData/blob/master/R/findWBD.R)
