### ISSUE TITLE
coveralls setup

### ISSUE THREAD

**Issue by dblodgett-usgs** [mikejohnson51/HydroData#3]
@dblodgett-usgs will get this setup over in his repo then we'll transfer here.

**Comment by dblodgett-usgs** [comment]
Looks like this isn't quite setup? Did you get a coveralls account set and turn the repo on in there?

**Comment by mikejohnson51** [comment]
I am struggling with this now. I got an account and turned on the repo:

Its here: https://coveralls.io/github/mikejohnson51/HydroData

**Comment by mikejohnson51** [comment]
I had to rebuild the Travis call. Is there something similar here that Im missing?

**Comment by dblodgett-usgs** [comment]
Alright. no, it should show up. Hang tight, I've got a PR coming soon. I think it'll work its self out.

**Comment by dblodgett-usgs** [comment]
We have a badge! It's a sad badge, but it's a badge! ⭐️ ![](https://coveralls.io/repos/github/mikejohnson51/HydroData/badge.svg?branch=master)   

![](http://www.oscarchamps.com/wp-content/uploads/2015/04/1948-Treasure-of-the-Sierra-Madre-The-06.jpg)

**Comment by mikejohnson51** [comment]
Haha 0% is rarely ideal. I just started reading about this how does it improve?!

**Comment by dblodgett-usgs** [comment]
Coveralls knows what lines of code ran when the tests ran. The more lines of code that the tests touch, the higher that percentage gets. Here's a package that shows a bit more of what it can look like. https://coveralls.io/github/USGS-R/netcdf.dsg?branch=master
