### ISSUE TITLE
Implement starter vignette and link to rawgit view of it in readme

### ISSUE THREAD

**Issue by dblodgett-usgs** [mikejohnson51/HydroData#4]
probably best to use "dev" rawgit since the "production" rawgit doesn't update through time very well.

**Comment by mikejohnson51** [comment]
Excellent, this took me longer then expected to figure out! I have uploaded the one I sent you with some additions as well as a starting vignette for defining an AOI. Will start to rework the readme from there.

**Comment by dblodgett-usgs** [comment]
Looks good! 👍It's a good practice to reference issues in your commits. We can also link to commits from issues though. So this issue is fixed by e55e1b4bcdabe863bf13f4fc5efbd9e5235d79ec and 705ad4314431e118afdcdd523cf999d452fff59b
