### ISSUE TITLE
Create issues for planning implementation of test coverage

### ISSUE THREAD

**Issue by dblodgett-usgs** [mikejohnson51/HydroData#5]
Close this once a plan is documented in a set of issues for implementation of test coverage of important functions in the package.

**Comment by mikejohnson51** [comment]
Please see the 'restructure' branch for updates. These include: 
Moving AOI functions to a separate package (useful for this as well as the NWM package development)
Building test cases
Reducing dependencies

**Comment by mikejohnson51** [comment]
The plan is to iteratively add each function back into the restructure branch
