### ISSUE TITLE
Does HydroData actually use sf package?

### ISSUE THREAD

**Issue by dblodgett-usgs** [mikejohnson51/HydroData#6]
sf is great. I use the heck out of it, but it's a little tricky with travis testing. Is it actually used in the package right now?

**Comment by mikejohnson51** [comment]
Yes and no. The USAboundaries package delivers spatial objects as sf objects. I convert them to sp objects in getFiatBoundary script (lines 47-52)

If memory serves, I needed the sf package for this conversion. That is the only use though so maybe there are better ways. I can look into it!

**Comment by mikejohnson51** [comment]
Yes and no. The USAboundaries package delivers spatial objects as sf objects. I convert them to sp objects in getFiatBoundary script (lines 47-52)

If memory serves, I needed the sf package for this conversion. That is the only use though so maybe there are better ways. I can look into it!

**Comment by dblodgett-usgs** [comment]
Alright. We can figure out how to get travis to build sf.
